# Generated by Django 6.0 on 2026-01-05 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200, verbose_name='Tên thuốc/TPCN')),
                ('gia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán (VNĐ)')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Công dụng/Mô tả')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='san_pham/', verbose_name='Ảnh sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuyen_khoa', models.CharField(max_length=100, verbose_name='Chuyên khoa')),
                ('gioi_thieu', models.TextField(blank=True, verbose_name='Giới thiệu bác sĩ')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='bac_si/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='LichHen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gio', models.DateTimeField(verbose_name='Ngày giờ khám')),
                ('trieu_chung', models.TextField(verbose_name='Triệu chứng ban đầu')),
                ('trang_thai', models.CharField(choices=[('CHO_DUYET', 'Chờ duyệt'), ('DA_DUYET', 'Đã duyệt'), ('DA_KHAM', 'Đã khám'), ('HUY', 'Hủy bỏ')], default='CHO_DUYET', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('bac_si', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bacsi', verbose_name='Bác sĩ phụ trách')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_kham', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
            ],
        ),
        migrations.CreateModel(
            name='HoSoBenhAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuan_doan', models.TextField(verbose_name='Chẩn đoán của bác sĩ')),
                ('don_thuoc', models.TextField(verbose_name='Đơn thuốc / Lời dặn')),
                ('file_ket_qua', models.FileField(blank=True, null=True, upload_to='ket_qua_kham/', verbose_name='File kết quả (X-Quang/Siêu âm)')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('lich_hen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.lichhen', verbose_name='Theo lịch hẹn')),
            ],
        ),
    ]
